### ISSUE TITLE
Using command /wt no response

### ISSUE THREAD

**Issue by KEVIN910919** [EnvyWare/WonderTrade-Forge#11]
I am using WonderTrade with magma
But using the command /wt nothing happens
my English is not good (google translate)

Minecraft version: 1.12.2 in Magma 761933c-STABLE
WonderTrade-Forge version: 5.2.4-1.12.2
Server software: Windows10

**Comment by HanQianShui** [comment]
Me too
Using the command /wt nothing happens
Not even a hint

**Comment by HanQianShui** [comment]
If you find a solution, please share it.
Thank you for your help

**Comment by danorris709** [comment]
Are there any errors in the console log when you run the command, or join the server?

**Comment by KEVIN910919** [comment]
I found that changing the ip: 0.0.0.0 in config.yml to localhost works fine
my English is not good (google translate)

**Comment by HanQianShui** [comment]
> 

No 
The console did't respond
Only commands

**Comment by danorris709** [comment]
As indicated by the original poster; this is an issue with your config

**Comment by HanQianShui** [comment]
I don't know haw to set the database-details
