### ISSUE TITLE
When you try trading Pokemon form Wondertrade the Server crashes

### ISSUE THREAD

**Issue by goreziller** [EnvyWare/WonderTrade-Forge#15]
I connected the database in Wondertrade and made no other changes. If you enter /wondertrade, then select the pokemon you want to trade and then confirm, the server crashes with the following crash log.
https://pastebin.com/kxJmjrBn

**Comment by danorris709** [comment]
Was the wonder trade pool empty?

**Comment by goreziller** [comment]
No, the pool.json has a lot of Pokemon in it
https://pastebin.com/4vdLEnbV

**Comment by danorris709** [comment]
Fixed in latest
