### ISSUE TITLE
[6.0.2] Error on GUI open

### ISSUE THREAD

**Issue by goreziller** [EnvyWare/WonderTrade-Forge#16]
I have updated Wondertrade to 6.0.2 and now I get this error in the console when trying to open the GUI
https://pastebin.com/SHMPaz0h

**Comment by danorris709** [comment]
You need to stop the server, delete the pool.json file, then start the server again.

**Comment by danorris709** [comment]
You are not using the latest version of either Pixelmon or WonderTrade.
