### ISSUE TITLE
/wt <slot> can be used to bypass the level restriction

### ISSUE THREAD

**Issue by griffindeed** [EnvyWare/WonderTrade-Forge#19]
WonderTrade 6.0.2 (and the latest for 1.12) are both affected

**Comment by danorris709** [comment]
Can you provide more detail as to what the "level restriction" is, and how to replicate this?

**Comment by griffindeed** [comment]
By level restriction I was referring to the "min-required-level:" option in the config. It works when using the GUI but doesn't stop a player from using the running /wt command to bypass it. Made a short video of me doing it on my 1.16 test server. The process looked/worked the same in the 1.12 latest except for I didn't have to double click to select.
https://youtu.be/JVaHmZjMliA

**Comment by danorris709** [comment]
Fixed in next version
