### ISSUE TITLE
All Pokemon from WonderTrade have 0 IVs

### ISSUE THREAD

**Issue by Mikirae** [EnvyWare/WonderTrade-Forge#20]
![image](https://user-images.githubusercontent.com/24925669/180090094-5d936487-b239-4921-8d79-8afbbe0579a1.png)

**Comment by danorris709** [comment]
What Pokemon was this? One generated as a default or one added by a user and then saved?

**Comment by Mikirae** [comment]
This was a default generated one fresh from the pool. No one else had
wondertraded yet, and I was told that it happens to all natural Pokemon,
but couldn't confirm on player-traded ones as I didn't find any when I was
trading

**Comment by danorris709** [comment]
Fixed in next version
