### ISSUE TITLE
WonderTrade resets the OT of Pokemon put into it to your OT

### ISSUE THREAD

**Issue by Mikirae** [EnvyWare/WonderTrade-Forge#21]
This is an issue for anything that uses OT for the PokeDex, as well as anyone that blocks breeding unless you're the OT of that Pokemon

**Comment by Mikirae** [comment]
I meant to say that it will change the OT of the Pokémon to whoever gets it from WonderTrade, even if it was someone else’s Pokémon to begin with :)

**Comment by danorris709** [comment]
Again, is this with Pokemon added by another user or the default ones generated by the mod?

**Comment by Mikirae** [comment]
Thought I commented it, but this is when a player trades it to WonderTrade
and someone else receives it
For example:
Daniel trade's his Primeape to the WonderTrade with his OT on it
Mikirae receives said Primeape. The Primeape now has Mikirae's OT

**Comment by danorris709** [comment]
Seems like it could be a Pixelmon bug as I do not touch the OT

**Comment by Mikirae** [comment]
I haven't seen anything mess with it. Guess it could be related to the 0 IV
thing? Maybe it's resetting all stats? Not too sure. I could set the pool
to be like 5 mons and just spam wondertrade it until I get mine?

**Comment by Mikirae** [comment]
People have no idea what the fuck they're talking about and were making assumptions. Works just fine. Closing and sorry for bothering <3
