### ISSUE TITLE
Addition of a "/wt add <specs>" command to add Pokémon to WT via console

### ISSUE THREAD

**Issue by HackuJacku** [EnvyWare/WonderTrade-Forge#23]

**Comment by danorris709** [comment]
And how precisely would this world? The pool is of a given size so you cannot just "add" to it. You have to replace one of the members of the pool.

Nonetheless, you can do this through editing the file the pool is stored in anyway (assuming it's persistent)

**Comment by HackuJacku** [comment]
It could randomly replace a Pokémon, honestly not fussed on that, as long as I could add Pokémon (with the specs I define) from the console
