### ISSUE TITLE
1.16.5 WonderTrade Crash

### ISSUE THREAD

**Issue by VOrlando520** [EnvyWare/WonderTrade-Forge#26]
When choosing pokemon in menu, the hitting confirm, it crashes the entire server with the following crash report
https://pastebin.com/hSaZsBHL

**Comment by VOrlando520** [comment]
Still having this issue on the latest update when trying to hit confirm button to trade a pokemon

**Comment by danorris709** [comment]
Looks like your trade pool is empty. I have a fix to prevent the crash for the next version but obviously that's a bit of a problem!
