### ISSUE TITLE
Latest version requires java 11

### ISSUE THREAD

**Issue by StrangeOne101** [EnvyWare/WonderTrade-Forge#32]
# Description
Although the mod itself is compiled on Java 8, it shades in `com/envyful/wonder/trade/forge/shade/envy/api/database/Database` which is compiled in Java 11. This means the mod cannot be used in Java 8 or else a crash occurs

# Context
Pixelmon Version: 9.1.5
WT Version: 6.4.5
Java: 1.8.0_51

Crash Report: Same one in #33

**Comment by danorris709** [comment]
This is intentional - the mod is not support to be run on anything other than java 11
